### PR TITLE
Add replies to Self-Review Questionnaire: Security and Privacy.

### PR DESCRIPTION
**Pull request by fred-wang**
This PR adds a markdown file replying to the
"Self-Review Questionnaire: Security and Privacy." from the W3C
at https://w3ctag.github.io/security-questionnaire/#questions
See also #17

***
<a href="https://pr-preview.s3.amazonaws.com/fred-wang/mouse-events/pull/23.html" title="Last updated on Jul 6, 2023, 10:51 AM UTC (1175277)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/screen-share/captured-mouse-events/23/2c7a91f...fred-wang:1175277.html" title="Last updated on Jul 6, 2023, 10:51 AM UTC (1175277)">Diff</a>

### CODE REVIEW

**Comment by eladalon1983** [comment]
For index.html, I've drafted a similar version - could you PTAL at https://github.com/screen-share/captured-mouse-events/pull/25?

For the questionnaire - would you like to save it into an .md file and send a PR?

**Comment by fred-wang** [comment]
@eladalon1983 I commented on the other one. I'll modify this PR to put it in a md instead.

When checking the comment from W3C people I noticed they actually referred to the [editor's draft](https://w3ctag.github.io/security-questionnaire/) so I'll double check if there are some diffs.

**Comment by fred-wang** [comment]
@eladalon1983 done

**Comment by eladalon1983** [comment]
I'll merge this and iterate separately to save time. Thanks!!

**Comment by fred-wang** [comment]
OK thanks

**Pull request merged**
